### ISSUE TITLE
Playtime event is simply not happening

### ISSUE THREAD

**Issue by stgram** [CodeLanx/PlayTime#47]
While I do have multiple repeatable onlinetime events which work, and the on-login event fires every time, I cant seem to get any playtime events going on.
My config events variable is set to 1 (minute), which proves to be not a problem for my server.
My wannabe event by config is:

```
events:
  example:
    type: playtime
    time: 1200
    at-login: false
    repeat: false
    commands:
    - 'bcast %u just made 1200 minutes online!'
```

Yet it does not occur...
